### ISSUE TITLE
Materials API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#10]
## Description
This epic is a sub goal of the epic for Milestones API and provides information regarding materials. This epic requires few endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts our project management module as without materials we can't work on milestones. We want to be able to see all possible materials to choose from while ordering in milestones. However, it is not necessary implement before the Milestone Stages API.

### Hypothesis
The following is true by the end of this API

- [ ] We can query possible materials
- [ ] We can manage materials

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Materials #59 
- [ ] GET A Single Material #60 
- [ ] POST A New Material #61 
- [ ] PATCH A Material #62 
- [ ] DELETE A Material #63 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
1 week is needed to setup all the foundation, along with testing and documentation. No blockers expected.
