### ISSUE TITLE
Equipments API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#11]
## Description
This epic is a goal of the larger epic of Milestones API and contains functionality for equipment rentals in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This epic is a sub part of the Milestones API and is needed to provide management of equipment under a milestone. However, it is not necessary for  all milestones to require rented equipment so this API can be pushed towards the end.

### Hypothesis
The API must provide management of equipment under a milestone. This epic is considered complete when the following features are complete:

- [ ] Management and information of equipment
- [ ] Equipment Types
- [ ] #13 
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Equipment #64 
- [ ] GET All Equipment Types #70 
- [ ] GET A Single Equipment #65 
- [ ] POST A New Equipment #66 
- [ ] PATCH A Equipment #67 
- [ ] DELETE A Equipment #68 

## Stakeholders
None

## Timeline
3 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
The possible equipment types could be:
* tools
* heavy_vehicles
* machinery
* tunneling
* assistance
* others
