### ISSUE TITLE
Payments API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#12]
## Description
This epic is a sub goal of the epic for Milestones API and provides management of payments. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to see all create, manage, retrieve and summarize payments under a milestone. However, it is not necessary until to implement this till all other sub goals of a milestone are complete.

### Hypothesis
The following is true by the end of this API

- [ ] We can manage payments for a milestone
- [ ] We can choose a payment type for a payment. #14 

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Payments (Temporary - for testing only)
- [ ] GET A Single Payment (Temporary - for testing only)
- [ ] POST A New Payment #72 
- [ ] PATCH A Payment #74 
- [ ] DELETE A Payment #73 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
1 week is needed to setup all the foundation, along with testing and documentation. No blockers expected.
