### ISSUE TITLE
Rate Types API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#13]
## Description
This epic is a sub goal of the epic for Equipment API and provides information regarding rate types. This epic requires few endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to see all possible rate types so that we can assign a rate during equipment rental in milestones. However, it is not necessary until to implement this until we are working on the Equipment API.

### Hypothesis
The following is true by the end of this API

- [ ] We can query possible rate types
- [ ] We can manage rate types

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Rate Types #49 
- [ ] GET A Single Rate Type #50 
- [ ] POST A New Rate Type 🔒 #51 
- [ ] PATCH A Rate Type 🔒 #52 
- [ ] DELETE A Rate Type 🔒 #53 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

*Note: 🔒 symbol indicates the route is protected and accessible to **product owner** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
The possible rate types could be:
* hourly
* daily
* weekly
* monthly
* annually
* one-time
