### ISSUE TITLE
Payment Types API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#14]
## Description
This epic is a sub goal of the epic for Payments API and provides information regarding payment types. This epic requires few endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to see all possible reasons for a payment so that we can choose a type as reason during payment in milestones. However, it is not necessary until to implement this till we're working on the Payments API.

### Hypothesis
The following is true by the end of this API

- [ ] We can query possible payment types
- [ ] We can manage payment types

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Payment Types #54 
- [ ] GET A Single Payment Type #55 
- [ ] POST A New Payment Type 🔒 #56 
- [ ] PATCH A Payment Type 🔒 #57 
- [ ] DELETE A Payment Type 🔒 #58 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

*Note: 🔒 symbol indicates the route is protected and accessible to **product owner** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
The payment types are basically reasons for payment and could have possible values like:
- equipment payment
- labor payment
- material payment
