### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#2]
## Description
This epic is a goal of the larger epic of REST API and contains functionality for authentication in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This epic is a high impact goal as it provided the foundation for other API Epics.

### Hypothesis
The API must provide person authentication, request validation and request verification. This epic is considered complete when the following features are complete:

- [ ] Private API KEY/OAuth2 verification.
- [ ] Authorization token for each request.
- [ ] Person authentication procedures.
- [ ] Role based request access for each user.
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have person types and roles setup to control permissions in this API. This API only focuses on auth related tasks for persons, requests and apps.

## Stakeholders
None

## Timeline
2 weeks are needed to setup all the foundation, along with testing and documentation. No blockers so far
