### ISSUE TITLE
Roles API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#24]
## Description
This epic is a sub goal of the epic for Persons API and provides information regarding roles. This epic requires few endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to see all possible roles so that we can assign one to a person during account signup. This is the 1st API that should be worked on under Persons API, after Authentication API is complete.

### Hypothesis
The following is true by the end of this API

- [ ] We can query all possible roles
- [ ] We can query roles based on role type
- [ ] We can manage roles

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Roles #33 
- [ ] GET All Role Types 🔒 #69
- [ ] GET A Single Roles #34 
- [ ] POST A New Role 🔒  #35 
- [ ] PATCH A Role 🔒 #36 
- [ ] DELETE A Role 🔒 #37 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

*Note: 🔒 symbol indicates the route is protected and accessible to **product owner** only*

## Stakeholders
None

## Notes
A single role can have one of the following **role types**:
- `app_user`, used for contractors, inspectors, home owners etc.
- `laborer`, used for plumbers, electricians, carpenter etc.

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.
