### ISSUE TITLE
Permissions API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#26]
## Description
This epic is a sub goal of the epic for Permissions API and provides information regarding types of permissions. This epic requires few endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
We want to be able to see all possible permissions so that we can assign to a person for access control. This is the 2nd API that should be worked on under Persons API, after Authentication API is complete.

### Hypothesis
The following is true by the end of this API

- [ ] We can query possible permissions
- [ ] We can manage permissions

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Permissions 🔒 #42 
- [ ] GET A Single Permissions 🔒 #41  
- [ ] POST A New Permission 🔒 #38 
- [ ] PATCH A Permission 🔒 #39 
- [ ] DELETE A Permission 🔒 #40 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

*Note: 🔒 symbol indicates the route is protected and accessible to **product owner** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
Some `Permissions` are attached to the `Roles`. Making a person account with a certain role would automatically assign it certain permissions. e.g.

Creating `inspector` account would automatically assign it the following permissions:

Module Project Management - [Review]
Module Accounting - []
Module Labor Management - []
Module Material Management - [View Only]

Creating `on-site manager` account would automatically assign it the following permissions:

Module Project Management - [Attach Only]
Module Accounting - []
Module Labor Management - [View Only]
Module Material Management - [View, Update]
