### ISSUE TITLE
Laborer API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#4]
## Description
This epic is a goal of the larger epic of REST API and contains functionality for laborers management in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This epic is is essential to the working of the entire project but has to be implemented near the end of the REST API Epic.

### Hypothesis
The API must provide management for laborers. This epic is considered complete when the following features are complete:

- [ ] Laborer information
- [ ] Laborer assigning
- [ ] Laborer management
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have Authentication and Users API setup. In the end we need to have a collection of following endpoints:

- [ ] GET All Laborers #29 
- [ ] GET A Single Laborer #30 
- [ ] POST A New Laborer #28 
- [ ] PATCH A Laborer #32
- [ ] DELETE A Laborer #31 

## Stakeholders
None

## Timeline
1 weeks are needed to setup all the foundation, along with testing and documentation. No blockers so far
