### ISSUE TITLE
Projects API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#6]
## Description
This epic is a goal of the larger epic of REST API and contains functionality for project management in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This epic is a core part of the overall project.

### Hypothesis
The API must provide management and information for projects. This epic is considered complete when the following features are complete:

- [ ] Project Management
- [ ] Project Roles #24 
- [ ] Project Payments #12 
- [ ] Project Milestone #8 
- [ ] Project Equipment #11 
- [ ] Project Material #10 

## Acceptance criteria and must have scope
We must have Authentication and Persons API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Projects #81 
- [ ] GET Single Project #80 
- [ ] GET A Project's Milestones #82 
- [ ] GET A Project's Roles #83 
- [ ] GET A Project's Payments #75 
- [ ] GET A Project's Materials #84 
- [ ] POST A New Project #76 
- [ ] PATCH A Project #78 , #79 
- [ ] DELETE A Project #77 
- [ ] Documentation
- [ ] Tests

## Stakeholders
None

## Timeline
2 weeks are needed to setup all the foundation, along with testing and documentation plus an additional week to test the merged sub epics. The structure of materials and payments endpoint might change in order to reduce joins to improve search queries.

**Comment by arafaysaleem** [comment]
This Epic has 3 stages of work:

1. First 2 weeks for completing the base functionality of this API.
2. Remaining sub epics begin and complete 1 week before deadline.
3. Last 1 week to test combined functionality of the merged sub epics.
