### ISSUE TITLE
Labels API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#7]
## Description
This epic is a goal of the larger epic of Milestones API and contains functionality for label assignment in our project. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This epic is a sub part of the Milestones API.

### Hypothesis
The API must provide management of labels. This epic is considered complete when the following features are complete:

- [ ] Labels Management
- [ ] Documentation
- [ ] Tests

## Acceptance criteria and must have scope
We must have Authentication API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Labels #43 
- [ ] GET A Single Label #45 
- [ ] POST A New Label 🔒 #48 
- [ ] PATCH A Label 🔒 #47 
- [ ] DELETE A Label 🔒 #46 

*Note: 🔒 symbol indicates the route is protected and accessible to **product owner** only*

## Stakeholders
None

## Timeline
2 days are needed to setup all the foundation, along with testing and documentation. No blockers expected.
