### ISSUE TITLE
Milestones API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#8]
## Description
This epic is a sub goal of the epic for Projects API and provides functionality surrounding project milestones. This epic requires multiple endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts our project management module as without milestones we can't create tasks for our project and we can't proceed. We want to be able to divide a project into milestones each with it's own materials, stages, payments and equipment. We can track what labor is working on each milestone daily. We can assign labels to a milestone to indicate what is it's scope. We should work on this immediately after setting up Projects API.

### Hypothesis
The following is true by the end of this API

- [ ] We can query/manage possible milestones of a project
- [ ] We can query/manage stages in a milestone #9 
- [ ] We can query/manage ordered materials in a milestone #10 
- [ ] We can query/manage rented equipment in a milestone #11 
- [ ] We can query/manage payments in a milestone #12 
- [ ] We can query/manage labor activity on a milestone #4 
- [ ] We can query/manage labels on a milestone #7 

## Acceptance criteria and must have scope
We must have Authentication, Projects and Labors API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Milestones
- [ ] GET A Milestone's Stages
- [ ] GET A Milestone's Labor
- [ ] GET A Milestone's Labels
- [ ] GET A Milestone's Payments #71 
- [ ] GET A Milestone's Rented Equipment
- [ ] GET A Milestone's Ordered Materials
- [ ] GET A Single Milestone
- [ ] POST A New Milestone
- [ ] PATCH A Milestone
- [ ] DELETE A Milestone
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
5 weeks are needed to setup all the foundation, along with testing and documentation. No blockers expected.

**Comment by arafaysaleem** [comment]
This Epic has 3 stages:

1. First 3 starting days we will work on the base functionality of this API. 
2. Sub epics will begin and continue till 3 days before the deadline.
3. Remaining 3 days, after sub epics are complete, will be used to check each of their functionalities in combination for this API's endpoints e.g. **Get a milestone's stages** after `Stages API` complete.
