### ISSUE TITLE
Milestone Stages API

### ISSUE THREAD

**Issue by arafaysaleem** [cyntaria/ConstructionERP-Backend#9]
## Description
This epic is a sub goal of the epic for Milestones API and provides management and information of stages in a milestone. This epic requires few endpoints to be setup and tested along with their detailed documentation.

## Initiative / goal
This API impacts our project management module as without stages we can't progress the milestones. We want to be able to set different criteria stages in milestones to track progress. It is the first thing that we need to work on under Milestones API.

### Hypothesis
The following is true by the end of this API

- [ ] We can query possible stages
- [ ] We can manage stages

## Acceptance criteria and must have scope
We must have Authentication and Persons API setup prior to this. In the end we need to have a collection of following endpoints:

- [ ] GET All Stages #90 #91
- [ ] GET A Single Stage #89 
- [ ] POST A New Stage #85 
- [ ] PATCH A Stage #87 #88 
- [ ] DELETE A Stage #86 
- [ ] Documentation For Each Endpoint
- [ ] Tests For Each Endpoint

## Stakeholders
None

## Timeline
10 days are needed to setup all the foundation, along with testing and documentation. Using of project role id instead of person permission id might be something that will change and can cause a few endpoints to be refactored as well as their tests
